// AUTO-GENERATED by scripts/convert-hm.mjs — do not edit by hand.
// Harvest Moon world maps (backgrounds + collision + reciprocal exits).
export interface HmExit { to: string; tx: number; ty: number; w: number; h: number; }
export interface HmChunk { url: string; x: number; y: number; w: number; h: number; }
export interface HmMapDef {
  key: string; name: string; subtitle: string;
  w: number; h: number; tile: number;
  bg: string | null; chunks: HmChunk[] | null; mapImage: string;
  spawn: { tx: number; ty: number }; exits: HmExit[];
}
export const HM_MAPS: HmMapDef[] = [
  {
    "key": "animal-shop",
    "name": "Animal Shop",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 56,
    "tile": 20,
    "bg": "world/hm/bg/animal-shop.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/animal-shop.jpg",
    "spawn": {
      "tx": 32,
      "ty": 28
    },
    "exits": [
      {
        "to": "town",
        "tx": 28,
        "ty": 53,
        "w": 7,
        "h": 1
      }
    ]
  },
  {
    "key": "bar",
    "name": "Bar",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 52,
    "tile": 20,
    "bg": "world/hm/bg/bar.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/bar.jpg",
    "spawn": {
      "tx": 32,
      "ty": 26
    },
    "exits": [
      {
        "to": "town",
        "tx": 32,
        "ty": 49,
        "w": 7,
        "h": 1
      },
      {
        "to": "bedroom-bar",
        "tx": 32,
        "ty": 5,
        "w": 4,
        "h": 1
      }
    ]
  },
  {
    "key": "bedroom-bar",
    "name": "Bar — Bedroom",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 56,
    "tile": 20,
    "bg": "world/hm/bg/bedroom-bar.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/bedroom-bar.jpg",
    "spawn": {
      "tx": 32,
      "ty": 28
    },
    "exits": [
      {
        "to": "bar",
        "tx": 32,
        "ty": 53,
        "w": 4,
        "h": 1
      }
    ]
  },
  {
    "key": "bedroom-florist",
    "name": "Florist — Bedroom",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 56,
    "tile": 20,
    "bg": "world/hm/bg/bedroom-florist.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/bedroom-florist.jpg",
    "spawn": {
      "tx": 32,
      "ty": 28
    },
    "exits": [
      {
        "to": "florist",
        "tx": 24,
        "ty": 49,
        "w": 5,
        "h": 1
      }
    ]
  },
  {
    "key": "bedroom-manor",
    "name": "Manor — Bedroom",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 56,
    "tile": 20,
    "bg": "world/hm/bg/bedroom-manor.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/bedroom-manor.jpg",
    "spawn": {
      "tx": 32,
      "ty": 28
    },
    "exits": [
      {
        "to": "manor-hallway",
        "tx": 36,
        "ty": 14,
        "w": 4,
        "h": 1
      }
    ]
  },
  {
    "key": "bedroom-restaurant",
    "name": "Restaurant — Bedroom",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 52,
    "tile": 20,
    "bg": "world/hm/bg/bedroom-restaurant.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/bedroom-restaurant.jpg",
    "spawn": {
      "tx": 32,
      "ty": 26
    },
    "exits": [
      {
        "to": "restaurant",
        "tx": 24,
        "ty": 49,
        "w": 5,
        "h": 1
      }
    ]
  },
  {
    "key": "bedroom-tools",
    "name": "Tool Shop — Bedroom",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 56,
    "tile": 20,
    "bg": "world/hm/bg/bedroom-tools.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/bedroom-tools.jpg",
    "spawn": {
      "tx": 32,
      "ty": 28
    },
    "exits": [
      {
        "to": "tools",
        "tx": 24,
        "ty": 49,
        "w": 4,
        "h": 1
      }
    ]
  },
  {
    "key": "church",
    "name": "Church",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 118,
    "tile": 20,
    "bg": "world/hm/bg/church.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/church.jpg",
    "spawn": {
      "tx": 32,
      "ty": 59
    },
    "exits": [
      {
        "to": "town",
        "tx": 29,
        "ty": 116,
        "w": 7,
        "h": 1
      }
    ]
  },
  {
    "key": "florist",
    "name": "Florist",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 52,
    "tile": 20,
    "bg": "world/hm/bg/florist.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/florist.jpg",
    "spawn": {
      "tx": 32,
      "ty": 26
    },
    "exits": [
      {
        "to": "town",
        "tx": 33,
        "ty": 48,
        "w": 6,
        "h": 1
      },
      {
        "to": "bedroom-florist",
        "tx": 24,
        "ty": 6,
        "w": 4,
        "h": 1
      }
    ]
  },
  {
    "key": "fortuneteller",
    "name": "Fortune Teller",
    "subtitle": "Harvest Moon",
    "w": 56,
    "h": 52,
    "tile": 20,
    "bg": "world/hm/bg/fortuneteller.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/fortuneteller.jpg",
    "spawn": {
      "tx": 28,
      "ty": 26
    },
    "exits": [
      {
        "to": "town",
        "tx": 24,
        "ty": 49,
        "w": 7,
        "h": 2
      }
    ]
  },
  {
    "key": "manor",
    "name": "Manor",
    "subtitle": "Harvest Moon",
    "w": 108,
    "h": 50,
    "tile": 20,
    "bg": "world/hm/bg/manor.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/manor.jpg",
    "spawn": {
      "tx": 54,
      "ty": 25
    },
    "exits": [
      {
        "to": "town",
        "tx": 25,
        "ty": 43,
        "w": 7,
        "h": 1
      },
      {
        "to": "manor-hallway",
        "tx": 33,
        "ty": 8,
        "w": 4,
        "h": 1
      }
    ]
  },
  {
    "key": "manor-hallway",
    "name": "Manor Hallway",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 56,
    "tile": 20,
    "bg": "world/hm/bg/manor-hallway.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/manor-hallway.jpg",
    "spawn": {
      "tx": 32,
      "ty": 28
    },
    "exits": [
      {
        "to": "manor",
        "tx": 40,
        "ty": 41,
        "w": 7,
        "h": 1
      },
      {
        "to": "bedroom-manor",
        "tx": 17,
        "ty": 41,
        "w": 7,
        "h": 1
      }
    ]
  },
  {
    "key": "restaurant",
    "name": "Restaurant",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 52,
    "tile": 20,
    "bg": "world/hm/bg/restaurant.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/restaurant.jpg",
    "spawn": {
      "tx": 32,
      "ty": 26
    },
    "exits": [
      {
        "to": "town",
        "tx": 32,
        "ty": 49,
        "w": 7,
        "h": 1
      },
      {
        "to": "bedroom-restaurant",
        "tx": 24,
        "ty": 6,
        "w": 4,
        "h": 1
      }
    ]
  },
  {
    "key": "tools",
    "name": "Tool Shop",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 52,
    "tile": 20,
    "bg": "world/hm/bg/tools.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/tools.jpg",
    "spawn": {
      "tx": 32,
      "ty": 26
    },
    "exits": [
      {
        "to": "bedroom-tools",
        "tx": 24,
        "ty": 6,
        "w": 4,
        "h": 1
      },
      {
        "to": "town",
        "tx": 32,
        "ty": 49,
        "w": 7,
        "h": 1
      }
    ]
  },
  {
    "key": "town",
    "name": "Harvest Town",
    "subtitle": "Harvest Moon Village",
    "w": 192,
    "h": 248,
    "tile": 20,
    "bg": null,
    "chunks": [
      {
        "url": "world/hm/bg/town/0_0.png",
        "x": 0,
        "y": 0,
        "w": 2000,
        "h": 2000
      },
      {
        "url": "world/hm/bg/town/2000_0.png",
        "x": 2000,
        "y": 0,
        "w": 1840,
        "h": 2000
      },
      {
        "url": "world/hm/bg/town/0_2000.png",
        "x": 0,
        "y": 2000,
        "w": 2000,
        "h": 2000
      },
      {
        "url": "world/hm/bg/town/2000_2000.png",
        "x": 2000,
        "y": 2000,
        "w": 1840,
        "h": 2000
      },
      {
        "url": "world/hm/bg/town/0_4000.png",
        "x": 0,
        "y": 4000,
        "w": 2000,
        "h": 960
      },
      {
        "url": "world/hm/bg/town/2000_4000.png",
        "x": 2000,
        "y": 4000,
        "w": 1840,
        "h": 960
      }
    ],
    "mapImage": "world/hm/minimap/town.jpg",
    "spawn": {
      "tx": 96,
      "ty": 124
    },
    "exits": [
      {
        "to": "florist",
        "tx": 147,
        "ty": 50,
        "w": 6,
        "h": 2
      },
      {
        "to": "fortuneteller",
        "tx": 144,
        "ty": 146,
        "w": 4,
        "h": 2
      },
      {
        "to": "crossroads",
        "tx": 191,
        "ty": 102,
        "w": 1,
        "h": 6
      },
      {
        "to": "tools",
        "tx": 100,
        "ty": 211,
        "w": 4,
        "h": 1
      },
      {
        "to": "restaurant",
        "tx": 68,
        "ty": 211,
        "w": 5,
        "h": 1
      },
      {
        "to": "bar",
        "tx": 36,
        "ty": 211,
        "w": 4,
        "h": 1
      },
      {
        "to": "manor",
        "tx": 36,
        "ty": 31,
        "w": 4,
        "h": 1
      },
      {
        "to": "church",
        "tx": 88,
        "ty": 30,
        "w": 8,
        "h": 2
      },
      {
        "to": "animal-shop",
        "tx": 148,
        "ty": 214,
        "w": 4,
        "h": 1
      }
    ]
  },
  {
    "key": "crossroads",
    "name": "Crossroads",
    "subtitle": "The Crossroads",
    "w": 64,
    "h": 56,
    "tile": 20,
    "bg": "world/hm/bg/crossroads.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/crossroads.jpg",
    "spawn": {
      "tx": 32,
      "ty": 28
    },
    "exits": [
      {
        "to": "mountains",
        "tx": 26,
        "ty": 0,
        "w": 12,
        "h": 1
      },
      {
        "to": "town",
        "tx": 0,
        "ty": 23,
        "w": 1,
        "h": 16
      },
      {
        "to": "farm",
        "tx": 63,
        "ty": 23,
        "w": 1,
        "h": 17
      }
    ]
  },
  {
    "key": "mountain-home",
    "name": "Mountain Cabin",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 56,
    "tile": 20,
    "bg": "world/hm/bg/mountain-home.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/mountain-home.jpg",
    "spawn": {
      "tx": 32,
      "ty": 28
    },
    "exits": [
      {
        "to": "mountains",
        "tx": 29,
        "ty": 53,
        "w": 6,
        "h": 1
      }
    ]
  },
  {
    "key": "mountains",
    "name": "Mountains",
    "subtitle": "Wild Mountains",
    "w": 192,
    "h": 184,
    "tile": 20,
    "bg": "world/hm/bg/mountains.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/mountains.jpg",
    "spawn": {
      "tx": 96,
      "ty": 92
    },
    "exits": [
      {
        "to": "cave2",
        "tx": 41,
        "ty": 99,
        "w": 2,
        "h": 1
      },
      {
        "to": "mountain-home",
        "tx": 129,
        "ty": 131,
        "w": 3,
        "h": 1
      },
      {
        "to": "crossroads",
        "tx": 74,
        "ty": 183,
        "w": 16,
        "h": 1
      }
    ]
  },
  {
    "key": "cave1",
    "name": "Farm Cave",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 184,
    "tile": 20,
    "bg": "world/hm/bg/cave1.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/cave1.jpg",
    "spawn": {
      "tx": 32,
      "ty": 92
    },
    "exits": [
      {
        "to": "tool-shed",
        "tx": 20,
        "ty": 38,
        "w": 8,
        "h": 2
      },
      {
        "to": "farm",
        "tx": 52,
        "ty": 147,
        "w": 3,
        "h": 1
      }
    ]
  },
  {
    "key": "coop",
    "name": "Chicken Coop",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 56,
    "tile": 20,
    "bg": "world/hm/bg/coop.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/coop.jpg",
    "spawn": {
      "tx": 32,
      "ty": 28
    },
    "exits": [
      {
        "to": "farm",
        "tx": 29,
        "ty": 51,
        "w": 5,
        "h": 1
      }
    ]
  },
  {
    "key": "cow-shed",
    "name": "Cow Shed",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 92,
    "tile": 20,
    "bg": "world/hm/bg/cow-shed.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/cow-shed.jpg",
    "spawn": {
      "tx": 32,
      "ty": 46
    },
    "exits": [
      {
        "to": "farm",
        "tx": 29,
        "ty": 89,
        "w": 6,
        "h": 1
      }
    ]
  },
  {
    "key": "farm",
    "name": "Homestead Farm",
    "subtitle": "The Homestead",
    "w": 148,
    "h": 144,
    "tile": 20,
    "bg": "world/hm/bg/farm.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/farm.jpg",
    "spawn": {
      "tx": 74,
      "ty": 72
    },
    "exits": [
      {
        "to": "crossroads",
        "tx": 0,
        "ty": 104,
        "w": 2,
        "h": 16
      },
      {
        "to": "home",
        "tx": 32,
        "ty": 78,
        "w": 3,
        "h": 1
      },
      {
        "to": "coop",
        "tx": 112,
        "ty": 82,
        "w": 4,
        "h": 1
      },
      {
        "to": "tool-shed",
        "tx": 104,
        "ty": 114,
        "w": 3,
        "h": 1
      },
      {
        "to": "cow-shed",
        "tx": 80,
        "ty": 82,
        "w": 4,
        "h": 1
      }
    ]
  },
  {
    "key": "home",
    "name": "Farmhouse",
    "subtitle": "Harvest Moon",
    "w": 104,
    "h": 52,
    "tile": 20,
    "bg": "world/hm/bg/home.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/home.jpg",
    "spawn": {
      "tx": 52,
      "ty": 26
    },
    "exits": [
      {
        "to": "farm",
        "tx": 29,
        "ty": 48,
        "w": 6,
        "h": 2
      }
    ]
  },
  {
    "key": "tool-shed",
    "name": "Tool Shed",
    "subtitle": "Harvest Moon",
    "w": 64,
    "h": 56,
    "tile": 20,
    "bg": "world/hm/bg/tool-shed.png",
    "chunks": null,
    "mapImage": "world/hm/minimap/tool-shed.jpg",
    "spawn": {
      "tx": 32,
      "ty": 28
    },
    "exits": [
      {
        "to": "farm",
        "tx": 28,
        "ty": 51,
        "w": 7,
        "h": 1
      },
      {
        "to": "cave1",
        "tx": 28,
        "ty": 10,
        "w": 4,
        "h": 1
      }
    ]
  }
];
