import path from "node:path";
import { fileURLToPath } from "node:url";
import type { QuietAudioCategory } from "./catalog.js";

// ─────────────────────────────────────────────────────────────────────────────
// Curated Quiet Room source assets
//
// Discovered via the Openverse audio search API (license=cc0), then verified
// against each result's license_url / attribution fields. Preview MP3s are
// harvested into quiet-audio/sources/ for offline remix + redistribution.
//
// Openverse docs: https://docs.openverse.org/api/reference/search_algorithm.html
// API:            https://api.openverse.org/v1/audio/
// ─────────────────────────────────────────────────────────────────────────────

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** Bundled source root: artifacts/api-server/quiet-audio/sources */
export function quietSourcesRoot(): string {
  // generate.ts lives in …/bot/quiet/audio → four levels up to api-server package root
  return path.resolve(__dirname, "../../../../quiet-audio/sources");
}

export interface QuietSourceAsset {
  id: string;
  /** Relative path under quiet-audio/sources/ */
  file: string;
  title: string;
  category: QuietAudioCategory;
  openverseId: string;
  /** CDN / media URL used for harvest (usually Freesound preview via Openverse). */
  mediaUrl: string;
  foreignLandingUrl: string;
  creator: string;
  creatorUrl?: string;
  license: "cc0";
  licenseVersion: string;
  licenseUrl: string;
  attribution: string;
  provider: string;
  originalDurationMs: number;
  redistributionAllowed: true;
  commercialUseAllowed: true;
  modificationAllowed: true;
  fetchedVia: "openverse";
  notes?: string;
}

/**
 * Hand-picked CC0 clips. Each openverseId was confirmed `license: "cc0"` via
 * GET /v1/audio/?q=…&license=cc0 before harvest. Re-run
 * `node scripts/harvest-quiet-audio.mjs` to refresh files.
 */
export const QUIET_SOURCE_ASSETS: QuietSourceAsset[] = [
  // ── Rain ───────────────────────────────────────────────────────────────────
  {
    id: "src-rain-window-01",
    file: "rain/rain-on-roof-window.mp3",
    title: "Rain on Roof & Window",
    category: "rain",
    openverseId: "0b4d6414-c481-4fd9-a282-cca7c245e386",
    mediaUrl: "https://cdn.freesound.org/previews/103/103652_591891-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/palegolas/sounds/103652",
    creator: "palegolas",
    creatorUrl: "https://freesound.org/people/palegolas",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Rain_on_roofwindow_distant_traffic.mp3\" by palegolas is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 76800,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-rain-roof-01",
    file: "rain/rain-on-polycarbonate.mp3",
    title: "Rain on Roof",
    category: "rain",
    openverseId: "a902c2fd-6057-4050-830a-7f7b20f44882",
    mediaUrl: "https://cdn.freesound.org/previews/204/204338_2945960-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/dwareing/sounds/204338",
    creator: "dwareing",
    creatorUrl: "https://freesound.org/people/dwareing",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Rain on polycarbonate 2.flac\" by dwareing is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 539300,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-rain-gentle-01",
    file: "rain/gentle-rain.mp3",
    title: "Gentle Rain",
    category: "rain",
    openverseId: "4c1804e9-6944-48b4-b3d5-8e641ec0f265",
    mediaUrl: "https://cdn.freesound.org/previews/501/501243_8644110-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/shelbyshark/sounds/501243",
    creator: "shelbyshark",
    creatorUrl: "https://freesound.org/people/shelbyshark",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Gentle Rain.wav\" by shelbyshark is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 53300,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-rain-storm-01",
    file: "rain/rain-strong-thunder.mp3",
    title: "Soft Storm Rain",
    category: "rain",
    openverseId: "8708d33a-9c64-4111-a7d8-0acb64c983e6",
    mediaUrl: "https://cdn.freesound.org/previews/157/157486_2366774-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/loopbasedmusic/sounds/157486",
    creator: "loopbasedmusic",
    creatorUrl: "https://freesound.org/people/loopbasedmusic",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"rain_strong_with_thunders.aif\" by loopbasedmusic is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 122000,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-rain-woodland-01",
    file: "rain/light-rain-woodland.mp3",
    title: "Night Rain (Woodland)",
    category: "rain",
    openverseId: "d17d6090-87bb-4147-8417-d9055922da0a",
    mediaUrl: "https://cdn.freesound.org/previews/695/695571_5392691-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/thinkingfish/sounds/695571",
    creator: "thinkingfish",
    creatorUrl: "https://freesound.org/people/thinkingfish",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Light Rain on Woodland Floor and Running Stream.wav\" by thinkingfish is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 157100,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },

  // ── Ocean / water ──────────────────────────────────────────────────────────
  {
    id: "src-ocean-zen-01",
    file: "ocean/zen-ocean-waves.mp3",
    title: "Calm Ocean Waves",
    category: "ocean",
    openverseId: "b09fd453-95ae-4604-aab2-3b7c5cfb6b95",
    mediaUrl: "https://cdn.freesound.org/previews/456/456899_9518146-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/INNORECORDS/sounds/456899",
    creator: "INNORECORDS",
    creatorUrl: "https://freesound.org/people/INNORECORDS",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Zen Ocean Waves,Ocean Waves Ambience.mp3\" by INNORECORDS is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 95779,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-ocean-big-01",
    file: "ocean/big-waves.mp3",
    title: "Slow Waves",
    category: "ocean",
    openverseId: "01522247-b53f-44e2-92c6-ec620def6485",
    mediaUrl: "https://cdn.freesound.org/previews/426/426075_3380363-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/chris_dagorne/sounds/426075",
    creator: "chris_dagorne",
    creatorUrl: "https://freesound.org/people/chris_dagorne",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Big waves breaking and splashing against groyne\" by chris_dagorne is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 233100,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-ocean-by-sea-01",
    file: "ocean/by-the-sea.mp3",
    title: "Distant Beach",
    category: "ocean",
    openverseId: "873d8c72-3846-4de3-8df0-81db190f988c",
    mediaUrl: "https://cdn.freesound.org/previews/404/404696_7583126-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/OSFX/sounds/404696",
    creator: "OSFX",
    creatorUrl: "https://freesound.org/people/OSFX",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"By the sea\" by OSFX is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 78000,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-stream-01",
    file: "stream/stream-close.mp3",
    title: "Quiet Stream",
    category: "stream",
    openverseId: "8a9d7bbb-86d7-4992-8766-ac0b3cb3e53a",
    mediaUrl: "https://cdn.freesound.org/previews/433/433589_5618682-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/jackthemurray/sounds/433589",
    creator: "jackthemurray",
    creatorUrl: "https://freesound.org/people/jackthemurray",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Stream River Water Up Close\" by jackthemurray is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 68900,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-river-01",
    file: "stream/small-river.mp3",
    title: "Small River",
    category: "stream",
    openverseId: "210ac469-3163-477f-a79d-ea8c846a2fed",
    mediaUrl: "https://cdn.freesound.org/previews/459/459406_627541-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/Pfannkuchn/sounds/459406",
    creator: "Pfannkuchn",
    creatorUrl: "https://freesound.org/people/Pfannkuchn",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Small River 1 - Fast - Distant\" by Pfannkuchn is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 60000,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },

  // ── Fireplace / cozy ───────────────────────────────────────────────────────
  {
    id: "src-fire-01",
    file: "fireplace/crackling-fireplace.mp3",
    title: "Fireplace",
    category: "fireplace",
    openverseId: "914bb44e-4396-42e3-b369-b8d5ac5b793c",
    mediaUrl: "https://cdn.freesound.org/previews/563/563766_6253486-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/florianreichelt/sounds/563766",
    creator: "florianreichelt",
    creatorUrl: "https://freesound.org/people/florianreichelt",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"fire crackles\" by florianreichelt is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 50900,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
    notes: "Shorter CC0 crackle loop used instead of the multi-minute Aachen fireplace preview for faster harvest/remix.",
  },
  {
    id: "src-fire-stove-01",
    file: "fireplace/stove-fire.mp3",
    title: "Cabin Fire",
    category: "fireplace",
    openverseId: "077dfa8d-3541-4b63-967b-86e7bb8bc56c",
    mediaUrl: "https://cdn.freesound.org/previews/532/532191_9735871-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/mcmikai/sounds/532191",
    creator: "mcmikai",
    creatorUrl: "https://freesound.org/people/mcmikai",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Fire in the stove\" by mcmikai is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 60900,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },

  // ── Forest / nature / night ────────────────────────────────────────────────
  {
    id: "src-forest-night-01",
    file: "forest/forest-night-crickets.mp3",
    title: "Night Forest",
    category: "forest",
    openverseId: "951e6c56-5952-40ee-b652-bdc74e83374f",
    mediaUrl: "https://cdn.freesound.org/previews/328/328293_1661766-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/felix.blume/sounds/328293",
    creator: "felix.blume",
    creatorUrl: "https://freesound.org/people/felix.blume",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Forest at night, crickets, cicadas and insects…\" by felix.blume is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 300600,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-woods-01",
    file: "forest/woods-birds-wind.mp3",
    title: "Forest Air",
    category: "forest",
    openverseId: "eddd4878-7d54-4e61-a0e8-7d776b7e1d36",
    mediaUrl: "https://cdn.freesound.org/previews/665/665156_1661766-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/felix.blume/sounds/665156",
    creator: "felix.blume",
    creatorUrl: "https://freesound.org/people/felix.blume",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Woods ambience in Missouri…\" by felix.blume is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 576800,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-night-insects-01",
    file: "night/night-insects.mp3",
    title: "Night Sounds",
    category: "ambience",
    openverseId: "9e265dd8-00d7-43f8-a3cc-37d63e3dea58",
    mediaUrl: "https://cdn.freesound.org/previews/319/319941_989468-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/The_Sound_Side/sounds/319941",
    creator: "The_Sound_Side",
    creatorUrl: "https://freesound.org/people/The_Sound_Side",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Night Insects Lebanon .wav\" by The_Sound_Side is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 198800,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-night-quiet-01",
    file: "night/city-night-quiet.mp3",
    title: "Quiet Night",
    category: "ambience",
    openverseId: "cc72ea8f-aa5e-416b-b7c1-956f25fecfda",
    mediaUrl: "https://cdn.freesound.org/previews/197/197211_167260-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/ragamuffin/sounds/197211",
    creator: "ragamuffin",
    creatorUrl: "https://freesound.org/people/ragamuffin",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"city-night-quiet.wav\" by ragamuffin is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 239900,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },

  // ── Thunder / wind ─────────────────────────────────────────────────────────
  {
    id: "src-thunder-01",
    file: "thunder/distant-thunder.mp3",
    title: "Distant Thunder",
    category: "thunder",
    openverseId: "585e4db4-954b-4f46-9d3b-e71b27e43831",
    mediaUrl: "https://cdn.freesound.org/previews/107/107518_43834-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/sagetyrtle/sounds/107518",
    creator: "sagetyrtle",
    creatorUrl: "https://freesound.org/people/sagetyrtle",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"102610_distant_thunder_01.wav\" by sagetyrtle is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 151400,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-wind-beach-01",
    file: "wind/wind-on-beach.mp3",
    title: "Soft Wind",
    category: "wind",
    openverseId: "d39bff41-6124-4cef-8d33-57d32ab9a819",
    mediaUrl: "https://cdn.freesound.org/previews/130/130692_1483235-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/BrandonNyte/sounds/130692",
    creator: "BrandonNyte",
    creatorUrl: "https://freesound.org/people/BrandonNyte",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Wind on Beach\" by BrandonNyte is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 59300,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },

  // ── Music (CC0 ambient only) ───────────────────────────────────────────────
  {
    id: "src-music-pad-01",
    file: "music/angelic-pad-loop.mp3",
    title: "Soft Ambient Pad",
    category: "music",
    openverseId: "68e950c0-a4e0-47b8-a337-a7453e4a2c5f",
    mediaUrl: "https://cdn.freesound.org/previews/242/242773_3946286-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/PhonZz/sounds/242773",
    creator: "PhonZz",
    creatorUrl: "https://freesound.org/people/PhonZz",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Angelic Pad Loop.wav\" by PhonZz is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 1088000,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-music-dunes-01",
    file: "music/dunes-ambient.mp3",
    title: "Atmospheric Dunes",
    category: "music",
    openverseId: "0ce95b3a-c0a6-4cf7-b54b-907eae9f6a47",
    mediaUrl: "https://cdn.freesound.org/previews/447/447511_7038073-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/Andrewkn/sounds/447511",
    creator: "Andrewkn",
    creatorUrl: "https://freesound.org/people/Andrewkn",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Dunes\" by Andrewkn is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 296200,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-music-space-01",
    file: "music/ambient-space-texture.mp3",
    title: "Calm Synth Texture",
    category: "music",
    openverseId: "20502270-b305-450f-927f-1bc502814064",
    mediaUrl: "https://cdn.freesound.org/previews/474/474864_7038073-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/Andrewkn/sounds/474864",
    creator: "Andrewkn",
    creatorUrl: "https://freesound.org/people/Andrewkn",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Ambient Space Texture\" by Andrewkn is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 316100,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
  {
    id: "src-music-meditate-01",
    file: "music/meditate-calm-scape.mp3",
    title: "Meditation Scape",
    category: "music",
    openverseId: "7024ddfc-77f0-4ba9-b103-854bcea07127",
    mediaUrl: "https://cdn.freesound.org/previews/580/580073_2282212-hq.mp3",
    foreignLandingUrl: "https://freesound.org/people/szegvari/sounds/580073",
    creator: "szegvari",
    creatorUrl: "https://freesound.org/people/szegvari",
    license: "cc0",
    licenseVersion: "1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "\"Meditate Calm Scape\" by szegvari is marked with CC0 1.0.",
    provider: "freesound",
    originalDurationMs: 92900,
    redistributionAllowed: true,
    commercialUseAllowed: true,
    modificationAllowed: true,
    fetchedVia: "openverse",
  },
];

export function getSourceAsset(id: string): QuietSourceAsset | undefined {
  return QUIET_SOURCE_ASSETS.find(s => s.id === id);
}

export function sourceAbsPath(asset: QuietSourceAsset): string {
  return path.join(quietSourcesRoot(), asset.file);
}
