// ─────────────────────────────────────────────────────────────────────────────
// /emoji — turn any image into an animated emoji, generated by MakeEmoji.
//
// The command owns Discord: resolving what the user pointed at, deferring,
// replying, and the control panel. It contains no networking or automation of
// its own — generation goes through `generateEmoji`, which picks a provider and
// serves from cache when it can.
//
// Entry points, matching how index.ts routes interactions:
//   • handleEmojiCommand     — the slash command
//   • handleEmojiInteraction — components / modals whose customId starts `emoji:`
//   • handleEmojiAutocomplete — the manifest-backed option pickers
// ─────────────────────────────────────────────────────────────────────────────

import {
  AttachmentBuilder, MessageFlags,
  type AutocompleteInteraction, type ChatInputCommandInteraction, type Interaction,
  type MessageComponentInteraction, type ModalSubmitInteraction,
} from "discord.js";
import { logger } from "../../../lib/logger.js";
import { DISCORD_EMOJI_LIMIT, generateEmoji } from "../generate.js";
import type { GenerateOptions } from "../types.js";
import { EmojiError, toEmojiError } from "../utils/errors.js";
import { parseFormat, extensionFor } from "../utils/options.js";
import { loadSource } from "../utils/source.js";
import { toggleFavorite } from "./favorites.js";
import { defaultAnimation, isManifestOption, isPlaceholder, suggestFor } from "./options.js";
import {
  buildStylesPicker, buildStyleSearchModal, ensureStyleFocus, findStyle,
} from "./styles-picker.js";
import { buildCachedControlsReply, buildControls, buildUploadModal, describe, parseCid } from "./ui.js";
import { createSession, endSession, getSession, touchSession, type EmojiSession } from "./session.js";

/** Avatars are fetched large so there's detail to work with before downscaling. */
const AVATAR_SIZE = 512;

/** Where the image came from. */
interface Source { url: string; label: string }

/**
 * Pick the image to animate, in priority order: an explicit attachment, then a
 * named member's avatar, then a URL, and finally the caller's own avatar so the
 * command always does something useful with no options at all.
 */
function resolveSource(interaction: ChatInputCommandInteraction): Source {
  const attachment = interaction.options.getAttachment("image");
  if (attachment) {
    const type = attachment.contentType?.toLowerCase() ?? "";
    if (type && !type.startsWith("image/")) {
      throw new EmojiError("not_an_image", "That attachment isn't an image.");
    }
    return { url: attachment.url, label: attachment.name ?? "your upload" };
  }

  const user = interaction.options.getUser("user");
  if (user) {
    return {
      url: user.displayAvatarURL({ extension: "png", size: AVATAR_SIZE }),
      label: `${user.username}'s avatar`,
    };
  }

  const url = interaction.options.getString("url");
  if (url) return { url: url.trim(), label: "your link" };

  return {
    url: interaction.user.displayAvatarURL({ extension: "png", size: AVATAR_SIZE }),
    label: "your avatar",
  };
}

/** Session settings as a provider request. */
function toGenerateOptions(session: EmojiSession): GenerateOptions {
  return {
    image: session.image,
    animation: session.animation,
    format: session.format,
    ...(session.speed ? { speed: session.speed } : {}),
    ...(session.direction ? { direction: session.direction } : {}),
    ...(session.size ? { size: session.size } : {}),
    ...(session.color ? { color: session.color } : {}),
    ...(session.quality ? { quality: session.quality } : {}),
    ...(session.platform ? { platform: session.platform } : {}),
  };
}

/** Generate and build the Discord message payload. */
async function buildReply(session: EmojiSession, token: string) {
  const result = await generateEmoji(toGenerateOptions(session));

  session.lastResult = {
    buffer: result.buffer,
    format: result.format,
    bytes: result.bytes,
    providerId: result.providerId,
    cached: result.cached,
  };
  session.view = "controls";

  const file = new AttachmentBuilder(result.buffer, { name: `emoji.${extensionFor(result.format)}` });
  const lines = [
    describe(session, result.bytes, result.providerId, result.cached),
    `-# from ${session.sourceLabel}`,
  ];

  if (/avatar/i.test(session.sourceLabel)) {
    lines.push("-# Tip: tap **Upload image** to animate a Discord attachment instead of an avatar.");
  }

  if (result.bytes > DISCORD_EMOJI_LIMIT) {
    // Still send it — it's a perfectly good file, just not uploadable as a
    // custom emoji. Say so rather than handing over something that will be
    // rejected at the point of use.
    lines.push("-# ⚠️ Over Discord's 256 KB custom-emoji limit — try a smaller size or a different format.");
  }

  return {
    content: lines.join("\n"),
    embeds: [],
    files: [file],
    components: buildControls(session, token),
  };
}

/**
 * A failure reply that keeps the control panel when the session is still alive.
 *
 * Wiping the components on a transient error (MakeEmoji timing out, a rate
 * limit) stranded the user: the settings they had built up were still in the
 * session, but the only way back to them was re-running the command. Rebuilding
 * the panel lets them simply try again, or adjust a setting and retry.
 */
function failureReply(err: unknown, token?: string) {
  const session = token ? getSession(token) : undefined;
  return {
    content: failureMessage(err),
    files: [],
    embeds: [],
    components: session && token ? buildControls(session, token) : [],
  };
}

/** Turn any failure into a short, user-facing message. */
function failureMessage(err: unknown): string {
  const emojiError = toEmojiError(err);
  if (emojiError.code === "internal") {
    logger.error({ err }, "emoji command failed unexpectedly");
  }
  return `❌ ${emojiError.message}`;
}

export async function handleEmojiCommand(interaction: ChatInputCommandInteraction): Promise<void> {
  await interaction.deferReply();

  // Declared out here so the catch can rebuild the panel for a session that was
  // created before generation failed.
  let token: string | undefined;

  try {
    const source = resolveSource(interaction);
    const image = await loadSource(source.url);

    const chosen = interaction.options.getString("animation")?.trim();
    // The autocomplete placeholder is a prompt, not a value — a user can submit
    // it by pressing enter on the hint, and it must not reach the provider.
    const animation = chosen && !isPlaceholder(chosen) ? chosen : defaultAnimation();
    if (!animation) {
      // With no manifest there is no animation to default to, so say what's
      // missing rather than sending an empty request at the provider.
      throw new EmojiError(
        "provider_unavailable",
        "The emoji generator isn't set up on this server yet. An admin needs to run MakeEmoji discovery first.",
      );
    }

    /** A user-supplied option, ignoring the autocomplete placeholder. */
    const optional = (name: string) => {
      const value = interaction.options.getString(name)?.trim();
      return value && !isPlaceholder(value) ? value : undefined;
    };

    const created = createSession({
      image,
      ownerId: interaction.user.id,
      sourceLabel: source.label,
      animation,
      format: parseFormat(interaction.options.getString("format")),
      ...(optional("speed") ? { speed: optional("speed")! } : {}),
      ...(optional("direction") ? { direction: optional("direction")! } : {}),
      ...(optional("size") ? { size: optional("size")! } : {}),
      ...(optional("color") ? { color: optional("color")! } : {}),
      ...(optional("quality") ? { quality: optional("quality")! } : {}),
      ...(optional("platform") ? { platform: optional("platform")! } : {}),
    });
    token = created.token;

    await interaction.editReply(await buildReply(created.session, token));
  } catch (err) {
    await interaction.editReply(failureReply(err, token));
  }
}

export async function handleEmojiInteraction(interaction: Interaction): Promise<void> {
  if (!interaction.isMessageComponent() && !interaction.isModalSubmit()) return;

  const parsed = parseCid(interaction.customId);
  if (!parsed) return;

  const { action, token } = parsed;
  const session = getSession(token);

  if (!session) {
    await interaction.reply({
      content: "⌛ That emoji session has expired. Run `/emoji` again to start a new one.",
      flags: MessageFlags.Ephemeral,
    });
    return;
  }

  // The controls belong to whoever ran the command. Anyone else gets a private
  // nudge rather than silently hijacking the render.
  if (interaction.user.id !== session.ownerId) {
    await interaction.reply({
      content: "🔒 These controls belong to whoever ran `/emoji`. Run your own to get a set!",
      flags: MessageFlags.Ephemeral,
    });
    return;
  }

  if (action === "done") {
    if (!interaction.isMessageComponent()) return;
    endSession(token);
    await interaction.update({ components: [] });
    return;
  }

  // Style browser — search opens a modal; everything else re-renders the picker
  // (or regenerates when Apply is pressed).
  if (action.startsWith("styles")) {
    await handleStylesAction(interaction, session, token, action);
    return;
  }

  // Mid-session Discord upload — replace avatar (or any source) with an attachment.
  if (action === "upload" || action === "upload_modal") {
    await handleUploadAction(interaction, token, action);
    return;
  }

  if (!interaction.isMessageComponent()) return;

  const patch = patchFor(action, interaction);
  if (!patch) return;

  // Defer first: a generation can easily outlast Discord's 3-second window.
  await interaction.deferUpdate();

  const updated = touchSession(token, patch);
  if (!updated) return;

  try {
    await interaction.editReply(await buildReply(updated, token));
  } catch (err) {
    await interaction.editReply(failureReply(err, token));
  }
}

async function handleUploadAction(
  interaction: MessageComponentInteraction | ModalSubmitInteraction,
  token: string,
  action: string,
): Promise<void> {
  if (action === "upload" && interaction.isButton()) {
    await interaction.showModal(buildUploadModal(token)).catch(() => {});
    return;
  }

  if (action !== "upload_modal" || !interaction.isModalSubmit()) return;

  const files = interaction.fields.getUploadedFiles("image", false);
  const attachment = files?.first();
  if (!attachment) {
    await interaction.reply({
      content: "❌ No image was attached. Tap **Upload image** again and pick a file.",
      flags: MessageFlags.Ephemeral,
    }).catch(() => {});
    return;
  }

  const type = attachment.contentType?.toLowerCase() ?? "";
  if (type && !type.startsWith("image/")) {
    await interaction.reply({
      content: "❌ That attachment isn't an image. Upload a PNG, JPG, GIF, or WebP.",
      flags: MessageFlags.Ephemeral,
    }).catch(() => {});
    return;
  }

  await interaction.deferUpdate();

  try {
    const image = await loadSource(attachment.url);
    const updated = touchSession(token, {
      image,
      sourceLabel: attachment.name ?? "your upload",
      view: "controls",
      lastResult: undefined,
    });
    if (!updated) return;
    await interaction.editReply(await buildReply(updated, token));
  } catch (err) {
    await interaction.editReply(failureReply(err, token));
  }
}

async function handleStylesAction(
  interaction: MessageComponentInteraction | ModalSubmitInteraction,
  session: EmojiSession,
  token: string,
  action: string,
): Promise<void> {
  // Search button → modal (must not defer first).
  if (action === "styles_search" && interaction.isButton()) {
    await interaction.showModal(
      buildStyleSearchModal(token, session.styleQuery ?? ""),
    ).catch(() => {});
    return;
  }

  if (action === "styles_modal" && interaction.isModalSubmit()) {
    const query = interaction.fields.getTextInputValue("query").trim();
    await interaction.deferUpdate().catch(() => {});
    touchSession(token, {
      view: "styles",
      styleQuery: query,
      stylePage: 0,
      styleFocus: null,
    });
    const updated = getSession(token);
    if (!updated) return;
    await interaction.editReply(await buildStylesPicker(updated, token));
    return;
  }

  if (!interaction.isMessageComponent()) return;

  // Apply selected (or focused) style → regenerate with the user's image.
  if (action === "styles_apply" && interaction.isButton()) {
    await interaction.deferUpdate();
    const focus = ensureStyleFocus(session, session.ownerId);
    if (!findStyle(focus)) {
      await interaction.editReply(await buildStylesPicker(session, token));
      return;
    }
    const updated = touchSession(token, {
      animation: focus,
      styleFocus: focus,
      view: "controls",
    });
    if (!updated) return;
    try {
      await interaction.editReply(await buildReply(updated, token));
    } catch (err) {
      await interaction.editReply(failureReply(err, token));
    }
    return;
  }

  // Back to the control panel without regenerating when we still have a cache.
  if (action === "styles_back" && interaction.isButton()) {
    await interaction.deferUpdate();
    touchSession(token, { view: "controls" });
    const updated = getSession(token);
    if (!updated) return;
    const cached = buildCachedControlsReply(updated, token);
    if (cached) {
      await interaction.editReply(cached);
      return;
    }
    try {
      await interaction.editReply(await buildReply(updated, token));
    } catch (err) {
      await interaction.editReply(failureReply(err, token));
    }
    return;
  }

  await interaction.deferUpdate();

  if (action === "styles") {
    touchSession(token, {
      view: "styles",
      stylePage: 0,
      styleFocus: session.animation,
    });
  } else if (action === "styles_prev") {
    touchSession(token, {
      stylePage: Math.max(0, (session.stylePage ?? 0) - 1),
      styleFocus: null,
    });
  } else if (action === "styles_next") {
    touchSession(token, {
      stylePage: (session.stylePage ?? 0) + 1,
      styleFocus: null,
    });
  } else if (action === "styles_filter" && interaction.isButton()) {
    touchSession(token, {
      styleFilter: session.styleFilter === "favorites" ? "all" : "favorites",
      stylePage: 0,
      styleFocus: null,
    });
  } else if (action === "styles_fav" && interaction.isButton()) {
    const focus = ensureStyleFocus(session, session.ownerId);
    if (findStyle(focus)) toggleFavorite(session.ownerId, focus);
  } else if (action === "styles_pick" && interaction.isStringSelectMenu()) {
    const value = interaction.values[0];
    if (value && findStyle(value)) {
      touchSession(token, { styleFocus: value });
    }
  } else {
    return;
  }

  const updated = getSession(token);
  if (!updated) return;
  await interaction.editReply(await buildStylesPicker(updated, token));
}

/** Suggestions for the manifest-driven options. */
export async function handleEmojiAutocomplete(interaction: AutocompleteInteraction): Promise<void> {
  const focused = interaction.options.getFocused(true);
  if (!isManifestOption(focused.name)) {
    await interaction.respond([]);
    return;
  }
  await interaction.respond(suggestFor(focused.name, String(focused.value ?? "")));
}

/** Translate a control's customId action into a session patch. */
function patchFor(
  action: string,
  interaction: MessageComponentInteraction,
): Partial<EmojiSession> | null {
  if (interaction.isStringSelectMenu() && action.startsWith("set_")) {
    const key = action.slice("set_".length);
    const value = interaction.values[0];
    if (!value || !isManifestOption(key)) return null;
    // Values come straight from the manifest-built menu, and the provider
    // validates them again before anything is sent upstream.
    return { [key]: value } as Partial<EmojiSession>;
  }

  if (interaction.isButton() && action.startsWith("format_")) {
    return { format: parseFormat(action.slice("format_".length)) };
  }

  return null;
}
