// ─────────────────────────────────────────────────────────────────────────────
// /emoji — turn any image into an animated emoji, generated by MakeEmoji.
//
// The command owns Discord: resolving what the user pointed at, deferring,
// replying, and the control panel. It contains no networking or automation of
// its own — generation goes through `generateEmoji`, which picks a provider and
// serves from cache when it can.
//
// Entry points, matching how index.ts routes interactions:
//   • handleEmojiCommand     — the slash command
//   • handleEmojiInteraction — components / modals whose customId starts `emoji:`
//   • handleEmojiAutocomplete — the manifest-backed option pickers
// ─────────────────────────────────────────────────────────────────────────────

import {
  AttachmentBuilder, MessageFlags,
  type AutocompleteInteraction, type ButtonInteraction,
  type ChatInputCommandInteraction, type Interaction,
  type MessageComponentInteraction, type ModalSubmitInteraction,
  type UserSelectMenuInteraction,
} from "discord.js";
import { logger } from "../../../lib/logger.js";
import { DISCORD_EMOJI_LIMIT, generateEmoji } from "../generate.js";
import type { GenerateOptions } from "../types.js";
import { EmojiError, failureKind, toEmojiError } from "../utils/errors.js";
import { parseFormat, extensionFor } from "../utils/options.js";
import { loadSource } from "../utils/source.js";
import { toggleFavorite } from "./favorites.js";
import { defaultAnimation, isManifestOption, isPlaceholder, suggestFor } from "./options.js";
import {
  buildStylesPicker, buildStyleSearchModal, buildGotoPageModal, ensureStyleFocus,
  findStyle, pageStyles, totalStylePages,
} from "./styles-picker.js";
import {
  buildCachedControlsReply, buildControls, buildFinishScreen, buildPostPicker,
  buildServerModal, buildTargetChooser, buildUploadModal, describe, parseCid,
  resultFileName, RESULT_HINT,
} from "./ui.js";
import { createSession, endSession, getSession, touchSession, type EmojiSession } from "./session.js";
import { isSceneAnimation } from "../providers/offline/scene-pack.js";

/** Avatars are fetched large so there's detail to work with before downscaling. */
const AVATAR_SIZE = 512;

/** Where the image came from. */
interface Source { url: string; label: string }

/** Anything carrying a guild we can read an icon from. */
interface GuildCarrier {
  guild: { name: string; iconURL(options: { extension: "png"; size: number }): string | null } | null;
}

/** The guild's own icon, or null when the server has none set. */
function serverIconSource(interaction: GuildCarrier): Source | null {
  const guild = interaction.guild;
  const url = guild?.iconURL({ extension: "png", size: AVATAR_SIZE });
  return url ? { url, label: `${guild!.name}'s icon` } : null;
}

/**
 * Pick the image to animate, in priority order: an explicit attachment, then a
 * named member's avatar, then a URL, and finally the caller's own avatar so the
 * command always does something useful with no options at all.
 */
function resolveSource(interaction: ChatInputCommandInteraction): Source {
  const attachment = interaction.options.getAttachment("image");
  if (attachment) {
    const type = attachment.contentType?.toLowerCase() ?? "";
    if (type && !type.startsWith("image/")) {
      throw new EmojiError("not_an_image", "That attachment isn't an image.");
    }
    return { url: attachment.url, label: attachment.name ?? "your upload" };
  }

  const user = interaction.options.getUser("user");
  if (user) {
    return {
      url: user.displayAvatarURL({ extension: "png", size: AVATAR_SIZE }),
      label: `${user.username}'s avatar`,
    };
  }

  if (interaction.options.getBoolean("server")) {
    const icon = serverIconSource(interaction);
    if (!icon) throw new EmojiError("no_source", "This server doesn't have an icon set.");
    return icon;
  }

  const url = interaction.options.getString("url");
  if (url) return { url: url.trim(), label: "your link" };

  return {
    url: interaction.user.displayAvatarURL({ extension: "png", size: AVATAR_SIZE }),
    label: "your avatar",
  };
}

/** Session settings as a provider request. */
function toGenerateOptions(session: EmojiSession): GenerateOptions {
  if (!session.image) throw new EmojiError("no_source", "Pick something to animate first.");
  // Scenes are whole clips, not small MakeEmoji styles. The Size and Speed
  // controls DO apply — they set the final GIF's long edge and playback speed —
  // but the MakeEmoji-only side-controls (direction/colour/quality/platform)
  // don't map onto a composited scene, so those are dropped.
  const scene = isSceneAnimation(session.animation);
  return {
    image: session.image,
    animation: session.animation,
    format: session.format,
    ...(scene ? {
      ...(session.speed ? { speed: session.speed } : {}),
      ...(session.size ? { size: session.size } : {}),
    } : {
      ...(session.speed ? { speed: session.speed } : {}),
      ...(session.direction ? { direction: session.direction } : {}),
      ...(session.size ? { size: session.size } : {}),
      ...(session.color ? { color: session.color } : {}),
      ...(session.quality ? { quality: session.quality } : {}),
      ...(session.platform ? { platform: session.platform } : {}),
    }),
  };
}

/** Generate and build the Discord message payload. */
async function buildReply(session: EmojiSession, token: string) {
  if (!session.image) {
    // Every path that renders a result sets an image first; this guards the type
    // and turns a logic slip into a clean message rather than a crash.
    throw new EmojiError("no_source", "Pick something to animate first.");
  }
  const result = await generateEmoji(toGenerateOptions(session));

  session.lastResult = {
    buffer: result.buffer,
    format: result.format,
    bytes: result.bytes,
    providerId: result.providerId,
    cached: result.cached,
  };
  session.view = "controls";

  const file = new AttachmentBuilder(result.buffer, { name: resultFileName(result.buffer, result.format) });
  const sourceLabel = session.sourceLabel ?? "your image";
  const lines = [
    describe(session, result.bytes, result.providerId, result.cached),
    `-# from ${sourceLabel}`,
    RESULT_HINT,
  ];

  if (/avatar/i.test(sourceLabel)) {
    lines.push("-# Tip: tap **Upload image** to animate a Discord attachment instead of an avatar.");
  }

  if (!isSceneAnimation(session.animation) && result.bytes > DISCORD_EMOJI_LIMIT) {
    // Still send it — it's a perfectly good file, just not uploadable as a
    // custom emoji. Say so rather than handing over something that will be
    // rejected at the point of use.
    lines.push("-# ⚠️ Over Discord's 256 KB custom-emoji limit — try a smaller size or a different format.");
  }

  return {
    content: lines.join("\n"),
    embeds: [],
    files: [file],
    components: buildControls(session, token),
  };
}

/**
 * A failure reply that keeps the control panel when the session is still alive.
 *
 * Wiping the components on a transient error (MakeEmoji timing out, a rate
 * limit) stranded the user: the settings they had built up were still in the
 * session, but the only way back to them was re-running the command. Rebuilding
 * the panel lets them simply try again, or adjust a setting and retry.
 */
function failureReply(err: unknown, token?: string) {
  const session = token ? getSession(token) : undefined;
  return {
    content: failureMessage(err),
    files: [],
    embeds: [],
    components: session && token ? buildControls(session, token) : [],
  };
}

/**
 * Turn any failure into a short, user-facing message.
 *
 * The prefix and the follow-up line depend on what the user can actually do:
 * retrying a missing browser will never work, and telling someone their server
 * is misconfigured when MakeEmoji merely timed out sends them to an admin for
 * nothing.
 */
function failureMessage(err: unknown): string {
  const emojiError = toEmojiError(err);
  const kind = failureKind(err);

  if (emojiError.code === "internal") {
    logger.error({ err }, "emoji command failed unexpectedly");
  }

  switch (kind) {
    case "setup":
      return `🛠️ ${emojiError.message}`;
    case "transient":
      return `⏳ ${emojiError.message}\n-# This usually clears on its own — try again in a few seconds.`;
    default:
      return `❌ ${emojiError.message}`;
  }
}

export async function handleEmojiCommand(interaction: ChatInputCommandInteraction): Promise<void> {
  // The dashboard is a private workspace: only the caller acts on it, and the
  // clutter of browsing shouldn't sit in the channel. Sharing happens explicitly
  // through Post, which sends a real public message.
  await interaction.deferReply({ flags: MessageFlags.Ephemeral });

  /** A user-supplied option, ignoring the autocomplete placeholder. */
  const optional = (name: string) => {
    const value = interaction.options.getString(name)?.trim();
    return value && !isPlaceholder(value) ? value : undefined;
  };

  // Power-user fast path: if a target or a style was named on the command, honour
  // it and skip the chooser. Everything else opens the visual, target-first flow.
  const namedTarget = Boolean(
    interaction.options.getAttachment("image")
      || interaction.options.getUser("user")
      || interaction.options.getString("url")
      || interaction.options.getBoolean("server")
      || optional("animation"),
  );

  let token: string | undefined;

  try {
    const animation = optional("animation") ?? defaultAnimation();

    if (!namedTarget) {
      // The common case: no options. Create a session with no image yet and show
      // the "what do you want to animate?" screen. Picking a target loads the
      // source and drops straight into the style browser.
      const created = createSession({
        image: null,
        ownerId: interaction.user.id,
        sourceLabel: null,
        animation: animation ?? "",
        format: parseFormat(interaction.options.getString("format")),
        view: "target",
      });
      await interaction.editReply(buildTargetChooser(created.token));
      return;
    }

    const source = resolveSource(interaction);
    const image = await loadSource(source.url);

    if (!animation) {
      // With no manifest there is no animation to default to, so say what's
      // missing rather than sending an empty request at the provider.
      throw new EmojiError(
        "provider_unavailable",
        "The emoji generator isn't set up on this server yet. An admin needs to run MakeEmoji discovery first.",
      );
    }

    const created = createSession({
      image,
      ownerId: interaction.user.id,
      sourceLabel: source.label,
      animation,
      format: parseFormat(interaction.options.getString("format")),
      ...(optional("speed") ? { speed: optional("speed")! } : {}),
      ...(optional("direction") ? { direction: optional("direction")! } : {}),
      ...(optional("size") ? { size: optional("size")! } : {}),
      ...(optional("color") ? { color: optional("color")! } : {}),
      ...(optional("quality") ? { quality: optional("quality")! } : {}),
      ...(optional("platform") ? { platform: optional("platform")! } : {}),
    });
    token = created.token;

    await interaction.editReply(await buildReply(created.session, token));
  } catch (err) {
    await interaction.editReply(failureReply(err, token));
  }
}

export async function handleEmojiInteraction(interaction: Interaction): Promise<void> {
  if (!interaction.isMessageComponent() && !interaction.isModalSubmit()) return;

  const parsed = parseCid(interaction.customId);
  if (!parsed) return;

  const { action, token } = parsed;
  const session = getSession(token);

  if (!session) {
    await interaction.reply({
      content: "⌛ That emoji session has expired. Run `/emoji` again to start a new one.",
      flags: MessageFlags.Ephemeral,
    });
    return;
  }

  // The controls belong to whoever ran the command. Anyone else gets a private
  // nudge rather than silently hijacking the render.
  if (interaction.user.id !== session.ownerId) {
    await interaction.reply({
      content: "🔒 These controls belong to whoever ran `/emoji`. Run your own to get a set!",
      flags: MessageFlags.Ephemeral,
    });
    return;
  }

  // Done → the clean finish screen (bare emoji + Save/Post/Dismiss), not the
  // old settings-panel dump. The session stays alive so Post and Keep editing
  // still work; Dismiss is what actually ends it.
  if (action === "done") {
    if (!interaction.isMessageComponent()) return;
    if (!session.lastResult) {
      endSession(token);
      await interaction.update({ content: "✅ **Done!**", embeds: [], files: [], components: [] });
      return;
    }
    touchSession(token, { view: "finish" });
    await interaction.update(buildFinishScreen(session, token));
    return;
  }

  // Dismiss the whole dashboard — remove the ephemeral message entirely.
  if (action === "dismiss") {
    if (!interaction.isMessageComponent()) return;
    endSession(token);
    await interaction.deferUpdate().catch(() => {});
    await interaction.deleteReply().catch(() => {});
    return;
  }

  // From the finish screen, slip back into the editing panel without a re-render.
  if (action === "keep_editing") {
    if (!interaction.isMessageComponent()) return;
    await interaction.deferUpdate();
    const updated = touchSession(token, { view: "controls" });
    if (!updated) return;
    const reply = buildCachedControlsReply(updated, token) ?? await buildReply(updated, token);
    await interaction.editReply(reply);
    return;
  }

  // Style browser — search opens a modal; everything else re-renders the picker
  // (or regenerates when Apply is pressed).
  if (action.startsWith("styles")) {
    await handleStylesAction(interaction, session, token, action);
    return;
  }

  // Mid-session Discord upload — replace avatar (or any source) with an attachment.
  if (action === "upload" || action === "upload_modal") {
    await handleUploadAction(interaction, token, action);
    return;
  }

  // Opening screen: a target was chosen. Load it and drop into the style browser.
  if (action === "pick_user" && interaction.isUserSelectMenu()) {
    await handleTargetPick(interaction, token, "member");
    return;
  }
  if (action === "pick_me" && interaction.isButton()) {
    await handleTargetPick(interaction, token, "me");
    return;
  }
  // Favorites shortcut: jump straight to the starred styles on the caller's own
  // avatar. Target (on the board) lets them switch subject from there.
  if (action === "pick_fav" && interaction.isButton()) {
    touchSession(token, { styleFilter: "favorites", stylePage: 0, styleFocus: null });
    await handleTargetPick(interaction, token, "me");
    return;
  }
  // Server target: open a modal so the user can type a server ID (or leave it
  // blank for the current server), then resolve that guild's icon.
  if (action === "pick_server" && interaction.isButton()) {
    await interaction.showModal(buildServerModal(token)).catch(() => {});
    return;
  }
  if (action === "server_modal" && interaction.isModalSubmit()) {
    await handleServerModal(interaction, token);
    return;
  }

  if (action.startsWith("target_") && interaction.isButton()) {
    await handleTargetAction(interaction, session, token, action);
    return;
  }

  if (action.startsWith("post") && interaction.isMessageComponent()) {
    await handlePostAction(interaction, session, token, action);
    return;
  }

  if (!interaction.isMessageComponent()) return;

  const patch = patchFor(action, interaction);
  if (!patch) return;

  // Defer first: a generation can easily outlast Discord's 3-second window.
  await interaction.deferUpdate();

  const updated = touchSession(token, patch);
  if (!updated) return;

  try {
    await interaction.editReply(await buildReply(updated, token));
  } catch (err) {
    await interaction.editReply(failureReply(err, token));
  }
}

type PickKind = "member" | "me" | "server";

/**
 * A target was chosen on the opening screen. Resolve its image, store it, and
 * land in the style browser so the user immediately sees their own image under
 * each style.
 */
async function handleTargetPick(
  interaction: UserSelectMenuInteraction | ButtonInteraction,
  token: string,
  kind: PickKind,
): Promise<void> {
  let source: Source | null;

  if (kind === "member" && interaction.isUserSelectMenu()) {
    const user = interaction.users.first();
    source = user
      ? {
          url: user.displayAvatarURL({ extension: "png", size: AVATAR_SIZE }),
          label: `${user.username}'s avatar`,
        }
      : null;
  } else if (kind === "server") {
    source = serverIconSource(interaction);
  } else {
    source = {
      url: interaction.user.displayAvatarURL({ extension: "png", size: AVATAR_SIZE }),
      label: "your avatar",
    };
  }

  if (!source) {
    await interaction.reply({
      content: "❌ This server doesn't have an icon set. Pick a member or upload an image instead.",
      flags: MessageFlags.Ephemeral,
    }).catch(() => {});
    return;
  }

  await interaction.deferUpdate();
  await enterStyleBrowser(interaction, token, source);
}

/**
 * Resolve a server icon — the current guild, or a pasted server ID — and enter
 * the style browser on it.
 */
async function handleServerModal(
  interaction: ModalSubmitInteraction,
  token: string,
): Promise<void> {
  const raw = interaction.fields.getTextInputValue("server_id").trim();

  let source: Source | null;
  if (!raw) {
    source = serverIconSource(interaction);
  } else if (!/^\d{5,25}$/.test(raw)) {
    source = null;
    await interaction.reply({
      content: "❌ That doesn't look like a server ID. Right-click a server → Copy Server ID (needs Developer Mode).",
      flags: MessageFlags.Ephemeral,
    }).catch(() => {});
    return;
  } else {
    // The bot can only read icons for servers it is in.
    const guild = await interaction.client.guilds.fetch(raw).catch(() => null);
    const url = guild?.iconURL({ extension: "png", size: AVATAR_SIZE }) ?? null;
    source = url && guild ? { url, label: `${guild.name}'s icon` } : null;
    if (!source) {
      await interaction.reply({
        content: "❌ I couldn't get that server's icon — I need to be a member of it, and it must have an icon set.",
        flags: MessageFlags.Ephemeral,
      }).catch(() => {});
      return;
    }
  }

  if (!source) {
    await interaction.reply({
      content: "❌ This server doesn't have an icon set. Pick a member or upload an image instead.",
      flags: MessageFlags.Ephemeral,
    }).catch(() => {});
    return;
  }

  await interaction.deferUpdate();
  await enterStyleBrowser(interaction, token, source);
}

/**
 * Load `source` into the session and render the style browser.
 *
 * Shared by every way of choosing or changing a target. Any cached result from a
 * previous image is dropped — it belongs to the old subject, and keeping it
 * would let Apply or Post use the wrong one.
 */
async function enterStyleBrowser(
  interaction: MessageComponentInteraction | ModalSubmitInteraction,
  token: string,
  source: Source,
): Promise<void> {
  try {
    const image = await loadSource(source.url);
    const current = getSession(token);
    const updated = touchSession(token, {
      image,
      sourceLabel: source.label,
      view: "styles",
      stylePage: 0,
      styleFocus: current?.animation ?? null,
      lastResult: undefined,
    });
    if (!updated) return;
    await interaction.editReply(await buildStylesPicker(updated, token));
  } catch (err) {
    await interaction.editReply(failureReply(err, token));
  }
}

/** Swap the image being animated to the server icon or the caller's avatar. */
async function handleTargetAction(
  interaction: ButtonInteraction,
  session: EmojiSession,
  token: string,
  action: string,
): Promise<void> {
  const source = action === "target_server"
    ? serverIconSource(interaction)
    : {
        url: interaction.user.displayAvatarURL({ extension: "png", size: AVATAR_SIZE }),
        label: "your avatar",
      };

  if (!source) {
    await interaction.reply({
      content: "❌ This server doesn't have an icon set.",
      flags: MessageFlags.Ephemeral,
    }).catch(() => {});
    return;
  }

  await interaction.deferUpdate();

  try {
    const image = await loadSource(source.url);
    // The cached result belongs to the old image, so it must not survive a
    // target switch — otherwise Post would send the previous subject.
    const updated = touchSession(token, {
      image, sourceLabel: source.label, view: "controls", lastResult: undefined,
    });
    if (!updated) return;
    await interaction.editReply(await buildReply(updated, token));
  } catch (err) {
    await interaction.editReply(failureReply(err, token));
  }
}

/** Send the finished emoji to a channel the user picks. */
async function handlePostAction(
  interaction: MessageComponentInteraction,
  session: EmojiSession,
  token: string,
  action: string,
): Promise<void> {
  if (action === "post" && interaction.isButton()) {
    if (!session.lastResult) {
      await interaction.reply({
        content: "❌ Nothing to post yet — generate an emoji first.",
        flags: MessageFlags.Ephemeral,
      }).catch(() => {});
      return;
    }
    touchSession(token, { view: "post" });
    await interaction.update(buildPostPicker(session, token));
    return;
  }

  if (action === "post_back" && interaction.isButton()) {
    await interaction.deferUpdate();
    const updated = touchSession(token, { view: "controls" });
    if (!updated) return;
    // Reuse the stored bytes rather than regenerating just to redraw the panel.
    const reply = buildCachedControlsReply(updated, token);
    if (reply) await interaction.editReply(reply);
    return;
  }

  if (action !== "post_pick" || !interaction.isChannelSelectMenu()) return;

  const result = session.lastResult;
  const channelId = interaction.values[0];
  if (!result || !channelId) return;

  await interaction.deferUpdate();

  try {
    const channel = await interaction.client.channels.fetch(channelId);
    if (!channel?.isTextBased() || !("send" in channel)) {
      throw new EmojiError("internal", "That channel can't receive messages.");
    }

    // Just the file — no content, no author framing — so it lands in the
    // channel like a plain gif someone dropped, not a bot announcement.
    await channel.send({
      files: [new AttachmentBuilder(result.buffer, {
        name: `emoji.${extensionFor(result.format)}`,
      })],
    });

    const updated = touchSession(token, { view: "controls" }) ?? session;
    const reply = buildCachedControlsReply(updated, token);
    if (reply) await interaction.editReply(reply);
    await interaction.followUp({
      content: `✅ Posted to <#${channelId}>.`,
      flags: MessageFlags.Ephemeral,
    }).catch(() => {});
  } catch (err) {
    // A missing-permissions failure is the common case and is the user's to fix,
    // so it is reported plainly rather than logged as a bot fault.
    logger.warn(
      { err: err instanceof Error ? err.message : String(err), channelId },
      "could not post emoji to channel",
    );
    await interaction.followUp({
      content: "❌ Couldn't post there — I may not have permission to send messages or attach files in that channel.",
      flags: MessageFlags.Ephemeral,
    }).catch(() => {});
  }
}


async function handleUploadAction(
  interaction: MessageComponentInteraction | ModalSubmitInteraction,
  token: string,
  action: string,
): Promise<void> {
  if (action === "upload" && interaction.isButton()) {
    await interaction.showModal(buildUploadModal(token)).catch(() => {});
    return;
  }

  if (action !== "upload_modal" || !interaction.isModalSubmit()) return;

  const files = interaction.fields.getUploadedFiles("image", false);
  const attachment = files?.first();
  if (!attachment) {
    await interaction.reply({
      content: "❌ No image was attached. Tap **Upload image** again and pick a file.",
      flags: MessageFlags.Ephemeral,
    }).catch(() => {});
    return;
  }

  const type = attachment.contentType?.toLowerCase() ?? "";
  if (type && !type.startsWith("image/")) {
    await interaction.reply({
      content: "❌ That attachment isn't an image. Upload a PNG, JPG, GIF, or WebP.",
      flags: MessageFlags.Ephemeral,
    }).catch(() => {});
    return;
  }

  await interaction.deferUpdate();

  try {
    await enterStyleBrowser(interaction, token, {
      url: attachment.url,
      label: attachment.name ?? "your upload",
    });
  } catch (err) {
    await interaction.editReply(failureReply(err, token));
  }
}

async function handleStylesAction(
  interaction: MessageComponentInteraction | ModalSubmitInteraction,
  session: EmojiSession,
  token: string,
  action: string,
): Promise<void> {
  // Search button → search-only modal (must not defer first).
  if (action === "styles_search" && interaction.isButton()) {
    await interaction.showModal(
      buildStyleSearchModal(token, session.styleQuery ?? ""),
    ).catch(() => {});
    return;
  }

  // Go to page button → a page-number-only modal.
  if (action === "styles_goto" && interaction.isButton()) {
    const { page, pages } = pageStyles(session, session.ownerId);
    await interaction.showModal(buildGotoPageModal(token, pages, page)).catch(() => {});
    return;
  }

  if (action === "styles_modal" && interaction.isModalSubmit()) {
    const query = interaction.fields.getTextInputValue("query").trim();
    await interaction.deferUpdate().catch(() => {});

    // A changed search jumps to the first page of the new results; an unchanged
    // one leaves the user where they were.
    const queryChanged = query !== (session.styleQuery ?? "");
    touchSession(token, {
      view: "styles", styleQuery: query, styleFocus: null,
      ...(queryChanged ? { stylePage: 0 } : {}),
    });
    const updated = getSession(token);
    if (!updated) return;
    await interaction.editReply(await buildStylesPicker(updated, token));
    return;
  }

  if (action === "styles_goto_modal" && interaction.isModalSubmit()) {
    const pageRaw = interaction.fields.getTextInputValue("page").trim();
    await interaction.deferUpdate().catch(() => {});
    const requested = Number.parseInt(pageRaw, 10);
    if (pageRaw && Number.isFinite(requested)) {
      // 1-based in the UI, 0-based internally, clamped to the real range.
      const maxPage = totalStylePages(session, session.ownerId) - 1;
      touchSession(token, {
        stylePage: Math.min(Math.max(0, requested - 1), maxPage),
        styleFocus: null,
      });
    }
    const updated = getSession(token);
    if (!updated) return;
    await interaction.editReply(await buildStylesPicker(updated, token));
    return;
  }

  if (!interaction.isMessageComponent()) return;

  // Apply selected (or focused) style → regenerate with the user's image.
  if (action === "styles_apply" && interaction.isButton()) {
    await interaction.deferUpdate();
    const focus = ensureStyleFocus(session, session.ownerId);
    if (!findStyle(focus)) {
      await interaction.editReply(await buildStylesPicker(session, token));
      return;
    }
    const updated = touchSession(token, {
      animation: focus,
      styleFocus: focus,
      view: "controls",
    });
    if (!updated) return;
    try {
      await interaction.editReply(await buildReply(updated, token));
    } catch (err) {
      await interaction.editReply(failureReply(err, token));
    }
    return;
  }

  // Change target from inside the board — return to the opening chooser, keeping
  // the session so the picked style survives the round-trip.
  if (action === "styles_target" && interaction.isButton()) {
    await interaction.deferUpdate();
    touchSession(token, { view: "target" });
    await interaction.editReply(buildTargetChooser(token));
    return;
  }

  // Back to the control panel without regenerating when we still have a cache.
  if (action === "styles_back" && interaction.isButton()) {
    await interaction.deferUpdate();
    touchSession(token, { view: "controls" });
    const updated = getSession(token);
    if (!updated) return;
    const cached = buildCachedControlsReply(updated, token);
    if (cached) {
      await interaction.editReply(cached);
      return;
    }
    try {
      await interaction.editReply(await buildReply(updated, token));
    } catch (err) {
      await interaction.editReply(failureReply(err, token));
    }
    return;
  }

  await interaction.deferUpdate();

  if (action === "styles") {
    // Returning to the browser (e.g. "Browse styles" from the panel) keeps the
    // page the user last left off on — not a jarring jump back to page 1 — and
    // focuses the style currently applied.
    touchSession(token, {
      view: "styles",
      styleFocus: session.animation,
    });
  } else if (action === "styles_prev") {
    touchSession(token, {
      stylePage: Math.max(0, (session.stylePage ?? 0) - 1),
      styleFocus: null,
    });
  } else if (action === "styles_next") {
    touchSession(token, {
      stylePage: (session.stylePage ?? 0) + 1,
      styleFocus: null,
    });
  } else if (action === "styles_filter" && interaction.isButton()) {
    touchSession(token, {
      styleFilter: session.styleFilter === "favorites" ? "all" : "favorites",
      stylePage: 0,
      styleFocus: null,
    });
  } else if (action === "styles_fav" && interaction.isButton()) {
    const focus = ensureStyleFocus(session, session.ownerId);
    if (findStyle(focus)) toggleFavorite(session.ownerId, focus);
  } else if (action.startsWith("styles_n") && interaction.isButton()) {
    // Number picker: the label is the 1-based cell, the action carries the
    // 0-based index into this page's styles.
    const index = Number.parseInt(action.slice("styles_n".length), 10);
    const { rows } = pageStyles(session, session.ownerId);
    const pick = Number.isInteger(index) ? rows[index] : undefined;
    if (pick) touchSession(token, { styleFocus: pick.value });
  } else if (action === "styles_page" && interaction.isStringSelectMenu()) {
    // Page-jump dropdown: value is the 0-based page index.
    const target = Number.parseInt(interaction.values[0] ?? "", 10);
    if (Number.isInteger(target)) {
      const maxPage = totalStylePages(session, session.ownerId) - 1;
      touchSession(token, {
        stylePage: Math.min(Math.max(0, target), maxPage),
        styleFocus: null,
      });
    }
  } else {
    return;
  }

  const updated = getSession(token);
  if (!updated) return;
  await interaction.editReply(await buildStylesPicker(updated, token));
}

/** Suggestions for the manifest-driven options. */
export async function handleEmojiAutocomplete(interaction: AutocompleteInteraction): Promise<void> {
  const focused = interaction.options.getFocused(true);
  if (!isManifestOption(focused.name)) {
    await interaction.respond([]);
    return;
  }
  await interaction.respond(suggestFor(focused.name, String(focused.value ?? "")));
}

/** Translate a control's customId action into a session patch. */
function patchFor(
  action: string,
  interaction: MessageComponentInteraction,
): Partial<EmojiSession> | null {
  if (interaction.isStringSelectMenu() && action.startsWith("set_")) {
    const key = action.slice("set_".length);
    const value = interaction.values[0];
    if (!value || !isManifestOption(key)) return null;
    // Values come straight from the manifest-built menu, and the provider
    // validates them again before anything is sent upstream.
    return { [key]: value } as Partial<EmojiSession>;
  }

  if (interaction.isButton() && action.startsWith("format_")) {
    return { format: parseFormat(action.slice("format_".length)) };
  }

  return null;
}
