// ─────────────────────────────────────────────────────────────────────────────
// /emoji — turn any image into an animated emoji, generated by MakeEmoji.
//
// The command owns Discord: resolving what the user pointed at, deferring,
// replying, and the control panel. It contains no networking or automation of
// its own — generation goes through `generateEmoji`, which picks a provider and
// serves from cache when it can.
//
// Two entry points, matching how index.ts routes interactions:
//   • handleEmojiCommand     — the slash command
//   • handleEmojiInteraction — components whose customId starts `emoji:`
//   • handleEmojiAutocomplete — the manifest-backed option pickers
// ─────────────────────────────────────────────────────────────────────────────

import {
  AttachmentBuilder, MessageFlags,
  type AutocompleteInteraction, type ChatInputCommandInteraction, type Interaction,
  type MessageComponentInteraction,
} from "discord.js";
import { logger } from "../../../lib/logger.js";
import { DISCORD_EMOJI_LIMIT, generateEmoji } from "../generate.js";
import type { GenerateOptions } from "../types.js";
import { EmojiError, toEmojiError } from "../utils/errors.js";
import { parseFormat } from "../utils/options.js";
import { loadSource } from "../utils/source.js";
import { defaultAnimation, isManifestOption, suggestFor } from "./options.js";
import { buildControls, describe, parseCid } from "./ui.js";
import { createSession, endSession, getSession, touchSession, type EmojiSession } from "./session.js";

/** Avatars are fetched large so there's detail to work with before downscaling. */
const AVATAR_SIZE = 512;

/** Where the image came from. */
interface Source { url: string; label: string }

/**
 * Pick the image to animate, in priority order: an explicit attachment, then a
 * named member's avatar, then a URL, and finally the caller's own avatar so the
 * command always does something useful with no options at all.
 */
function resolveSource(interaction: ChatInputCommandInteraction): Source {
  const attachment = interaction.options.getAttachment("image");
  if (attachment) {
    const type = attachment.contentType?.toLowerCase() ?? "";
    if (type && !type.startsWith("image/")) {
      throw new EmojiError("not_an_image", "That attachment isn't an image.");
    }
    return { url: attachment.url, label: attachment.name ?? "your upload" };
  }

  const user = interaction.options.getUser("user");
  if (user) {
    return {
      url: user.displayAvatarURL({ extension: "png", size: AVATAR_SIZE }),
      label: `${user.username}'s avatar`,
    };
  }

  const url = interaction.options.getString("url");
  if (url) return { url: url.trim(), label: "your link" };

  return {
    url: interaction.user.displayAvatarURL({ extension: "png", size: AVATAR_SIZE }),
    label: "your avatar",
  };
}

/** Session settings as a provider request. */
function toGenerateOptions(session: EmojiSession): GenerateOptions {
  return {
    image: session.image,
    animation: session.animation,
    format: session.format,
    ...(session.speed ? { speed: session.speed } : {}),
    ...(session.direction ? { direction: session.direction } : {}),
    ...(session.size ? { size: Number(session.size) } : {}),
    ...(session.color ? { color: session.color } : {}),
    ...(session.quality ? { quality: session.quality } : {}),
    ...(session.platform ? { platform: session.platform } : {}),
  };
}

/** Generate and build the Discord message payload. */
async function buildReply(session: EmojiSession, token: string) {
  const result = await generateEmoji(toGenerateOptions(session));

  const file = new AttachmentBuilder(result.buffer, { name: `emoji.${result.format}` });
  const lines = [
    describe(session, result.bytes, result.providerId, result.cached),
    `-# from ${session.sourceLabel}`,
  ];

  if (result.bytes > DISCORD_EMOJI_LIMIT) {
    // Still send it — it's a perfectly good file, just not uploadable as a
    // custom emoji. Say so rather than handing over something that will be
    // rejected at the point of use.
    lines.push("-# ⚠️ Over Discord's 256 KB custom-emoji limit — try a smaller size or a different format.");
  }

  return { content: lines.join("\n"), files: [file], components: buildControls(session, token) };
}

/** Turn any failure into a short, user-facing message. */
function failureMessage(err: unknown): string {
  const emojiError = toEmojiError(err);
  if (emojiError.code === "internal") {
    logger.error({ err }, "emoji command failed unexpectedly");
  }
  return `❌ ${emojiError.message}`;
}

export async function handleEmojiCommand(interaction: ChatInputCommandInteraction): Promise<void> {
  await interaction.deferReply();

  try {
    const source = resolveSource(interaction);
    const image = await loadSource(source.url);

    // With no manifest there is no animation to default to, so say what's
    // missing rather than sending an empty request at the provider.
    const animation = interaction.options.getString("animation")?.trim() || defaultAnimation();
    if (!animation) {
      throw new EmojiError(
        "provider_unavailable",
        "The emoji generator isn't set up on this server yet. An admin needs to run MakeEmoji discovery first.",
      );
    }

    const optional = (name: string) => interaction.options.getString(name)?.trim() || undefined;

    const { token, session } = createSession({
      image,
      ownerId: interaction.user.id,
      sourceLabel: source.label,
      animation,
      format: parseFormat(interaction.options.getString("format")),
      ...(optional("speed") ? { speed: optional("speed")! } : {}),
      ...(optional("direction") ? { direction: optional("direction")! } : {}),
      ...(optional("size") ? { size: optional("size")! } : {}),
      ...(optional("color") ? { color: optional("color")! } : {}),
      ...(optional("quality") ? { quality: optional("quality")! } : {}),
      ...(optional("platform") ? { platform: optional("platform")! } : {}),
    });

    await interaction.editReply(await buildReply(session, token));
  } catch (err) {
    await interaction.editReply({ content: failureMessage(err), files: [], components: [] });
  }
}

export async function handleEmojiInteraction(interaction: Interaction): Promise<void> {
  if (!interaction.isMessageComponent()) return;

  const parsed = parseCid(interaction.customId);
  if (!parsed) return;

  const { action, token } = parsed;
  const session = getSession(token);

  if (!session) {
    await interaction.reply({
      content: "⌛ That emoji session has expired. Run `/emoji` again to start a new one.",
      flags: MessageFlags.Ephemeral,
    });
    return;
  }

  // The controls belong to whoever ran the command. Anyone else gets a private
  // nudge rather than silently hijacking the render.
  if (interaction.user.id !== session.ownerId) {
    await interaction.reply({
      content: "🔒 These controls belong to whoever ran `/emoji`. Run your own to get a set!",
      flags: MessageFlags.Ephemeral,
    });
    return;
  }

  if (action === "done") {
    endSession(token);
    await interaction.update({ components: [] });
    return;
  }

  const patch = patchFor(action, interaction);
  if (!patch) return;

  // Defer first: a generation can easily outlast Discord's 3-second window.
  await interaction.deferUpdate();

  const updated = touchSession(token, patch);
  if (!updated) return;

  try {
    await interaction.editReply(await buildReply(updated, token));
  } catch (err) {
    await interaction.editReply({ content: failureMessage(err), files: [], components: [] });
  }
}

/** Suggestions for the manifest-driven options. */
export async function handleEmojiAutocomplete(interaction: AutocompleteInteraction): Promise<void> {
  const focused = interaction.options.getFocused(true);
  if (!isManifestOption(focused.name)) {
    await interaction.respond([]);
    return;
  }
  await interaction.respond(suggestFor(focused.name, String(focused.value ?? "")));
}

/** Translate a control's customId action into a session patch. */
function patchFor(
  action: string,
  interaction: MessageComponentInteraction,
): Partial<EmojiSession> | null {
  if (interaction.isStringSelectMenu() && action.startsWith("set_")) {
    const key = action.slice("set_".length);
    const value = interaction.values[0];
    if (!value || !isManifestOption(key)) return null;
    // Values come straight from the manifest-built menu, and the provider
    // validates them again before anything is sent upstream.
    return { [key]: value } as Partial<EmojiSession>;
  }

  if (interaction.isButton() && action.startsWith("format_")) {
    return { format: parseFormat(action.slice("format_".length)) };
  }

  return null;
}
