uploads = []

[[generated]]
id = "V7cJjUcB4cDu9_YPimlDw"
uri = "file://artifacts/dashboard/public/banner-welcome.png"
type = "image"
title = "welcome banner"

[[generated]]
id = "Ki69g9N9HFvFyGsfUX9G-"
uri = "file://artifacts/dashboard/public/banner-rules.png"
type = "image"
title = "rules banner"

[[generated]]
id = "DtqRQv04rpVO2xTNtHK6Z"
uri = "file://artifacts/dashboard/public/banner-commands.png"
type = "image"
title = "commands banner"

[[outputs]]
id = "hLT25KZHOUFKhjaPox_Ch"
uri = "file://dn-cards-backup.tar.gz"
type = "unspecified"
title = "DN Cards — Full Source Backup (May 27 2026)"

[[outputs]]
id = "cAtihCBF9flqZKrXwXdGP"
uri = "file://db-backup.sql.gz"
type = "unspecified"
title = "DN Cards Database Backup (compressed SQL)"

[[outputs]]
id = "UL67iOsHfFTGUIfo7LWf2"
uri = "file://db-backup.txt"
type = "text"
title = "DN Cards Database Backup (viewable as text)"

[[outputs]]
id = "_2YIRcw9Gi3Ur7CnT4SUY"
uri = "file://exports/dn-cards-backup.tar.gz"
type = "unspecified"
title = "DN Cards — Full Project Backup (.tar.gz)"

[[outputs]]
id = "AcevgjaY8545FyubOGNwo"
uri = "file://docs/dn-cards-commands.pdf"
type = "pdf"
title = "DN Cards Command Reference (PDF)"
