import { beforeEach, describe, expect, it, vi } from "vitest";
import { cacheKey, cacheStats, clearCache, withCache } from "../cache/index.js";
import type { GenerateOptions, GenerateResult } from "../types.js";

function options(patch: Partial<GenerateOptions> = {}): GenerateOptions {
  return {
    image: Buffer.from("source-image-bytes"),
    animation: "shake",
    speed: "normal",
    direction: "right",
    size: "128",
    color: "#ff0000",
    format: "gif",
    quality: "high",
    platform: "discord",
    ...patch,
  };
}

function result(bytes = 1024): GenerateResult {
  return {
    buffer: Buffer.alloc(bytes, 7),
    format: "gif",
    bytes,
    providerId: "makeemoji-browser",
    durationMs: 1234,
    cached: false,
  };
}

describe("cacheKey", () => {
  it("is stable for identical requests", () => {
    expect(cacheKey(options())).toBe(cacheKey(options()));
  });

  it("changes when the source image changes", () => {
    expect(cacheKey(options({ image: Buffer.from("other") })))
      .not.toBe(cacheKey(options()));
  });

  it("changes when any setting changes", () => {
    // Every one of these alters the generated bytes, so sharing an entry
    // across them would serve the wrong file.
    const settings: Partial<GenerateOptions>[] = [
      { animation: "spin" }, { speed: "fast" }, { direction: "left" },
      { size: "64" }, { color: "#00ff00" }, { format: "webp" },
      { quality: "low" }, { platform: "slack" },
    ];
    const base = cacheKey(options());
    for (const patch of settings) {
      expect(cacheKey(options(patch)), JSON.stringify(patch)).not.toBe(base);
    }
  });

  it("ignores fields that cannot change the output", () => {
    // `debug` only controls tracing, and a signal is per-request plumbing.
    expect(cacheKey(options({ debug: true }))).toBe(cacheKey(options()));
    expect(cacheKey(options({ signal: new AbortController().signal })))
      .toBe(cacheKey(options()));
  });

  it("keys on content, not identity, so the same image from any source hits", () => {
    // The same avatar arriving as an attachment and as a URL must share one entry.
    expect(cacheKey(options({ image: Buffer.from("source-image-bytes") })))
      .toBe(cacheKey(options()));
  });
});

describe("withCache", () => {
  beforeEach(() => clearCache());

  it("generates once and serves the repeat from cache", async () => {
    const generate = vi.fn(async () => result());

    const first = await withCache(options(), generate);
    const second = await withCache(options(), generate);

    expect(generate).toHaveBeenCalledTimes(1);
    expect(first.cached).toBe(false);
    expect(second.cached).toBe(true);
    expect(second.buffer.equals(first.buffer)).toBe(true);
  });

  it("does not share entries between different settings", async () => {
    const generate = vi.fn(async () => result());
    await withCache(options(), generate);
    await withCache(options({ animation: "spin" }), generate);
    expect(generate).toHaveBeenCalledTimes(2);
  });

  it("counts hits and misses", async () => {
    const generate = vi.fn(async () => result());
    await withCache(options(), generate);
    await withCache(options(), generate);
    await withCache(options(), generate);

    const stats = cacheStats();
    expect(stats.hits).toBe(2);
    expect(stats.misses).toBe(1);
    expect(stats.entries).toBe(1);
  });

  it("does not cache a failed generation", async () => {
    const generate = vi.fn(async () => { throw new Error("upstream down"); });
    await expect(withCache(options(), generate)).rejects.toThrow("upstream down");
    expect(cacheStats().entries).toBe(0);
  });

  it("bounds itself so image buffers cannot accumulate", async () => {
    // 400 distinct 256 KB results is ~100 MB — well past both ceilings.
    for (let i = 0; i < 400; i++) {
      await withCache(options({ image: Buffer.from(`image-${i}`) }), async () => result(256 * 1024));
    }
    const stats = cacheStats();
    expect(stats.entries).toBeLessThanOrEqual(120);
    expect(stats.bytes).toBeLessThanOrEqual(64 * 1024 * 1024);
  }, 30_000);

  it("skips storing a single oversized result rather than evicting everything", async () => {
    await withCache(options(), async () => result(1024));
    await withCache(options({ animation: "spin" }), async () => result(32 * 1024 * 1024));
    // The small entry survives; the huge one was never stored.
    expect(cacheStats().entries).toBe(1);
  });

  it("clears completely", async () => {
    await withCache(options(), async () => result());
    clearCache();
    expect(cacheStats()).toEqual({ entries: 0, bytes: 0, hits: 0, misses: 0 });
  });
});
