// ─────────────────────────────────────────────────────────────────────────────
// Manifest loading.
//
// The manifest is data, not code, so it can be regenerated by a discovery run in
// the environment that can actually reach MakeEmoji and dropped into the repo
// without a rebuild. It is read once and cached; `reloadManifest` exists so the
// discovery tooling and tests can swap it without restarting the bot.
//
// A manifest that fails validation is treated exactly like a missing one — the
// provider reports itself unavailable with the reason. A half-parsed manifest is
// worse than none, because it would send half-formed requests at a live site.
// ─────────────────────────────────────────────────────────────────────────────

import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { logger } from "../../../../lib/logger.js";
import { Manifest, OPTION_KEYS, type ControlSpec, type OptionKey } from "./types.js";

/** Where a discovery run writes its manifest, and where we read it from. */
export const MANIFEST_FILENAME = "manifest.json";

/** Override the manifest location without a rebuild (set by the operator). */
const ENV_PATH = "MAKEEMOJI_MANIFEST_PATH";

/** Where the manifest lives relative to a repo root. */
const SOURCE_RELATIVE =
  "artifacts/api-server/src/bot/emoji/providers/makeemoji/manifest.json";

function candidatePaths(): string[] {
  const override = process.env[ENV_PATH]?.trim();

  // Beside this module: the source tree in development, and `dist/` in
  // production because build.mjs copies it there. This is the path that should
  // normally win — everything below is a safety net for unusual layouts.
  const beside = fileURLToPath(new URL(MANIFEST_FILENAME, import.meta.url));

  const cwd = process.cwd();
  // The bot may be started from the repo root or from the package directory,
  // and a manifest regenerated by discovery may be dropped in either place. Walk
  // up a few levels so no single assumption about the working directory can
  // strand an otherwise valid manifest.
  const roots = [cwd, join(cwd, ".."), join(cwd, "..", ".."), join(cwd, "..", "..", "..")];

  return [
    ...(override ? [override] : []),
    beside,
    // Alongside the bundle, for a deploy that copies dist elsewhere.
    join(dirname(beside), "..", MANIFEST_FILENAME),
    ...roots.flatMap(root => [
      join(root, MANIFEST_FILENAME),
      join(root, "makeemoji", MANIFEST_FILENAME),
      join(root, SOURCE_RELATIVE),
    ]),
  ];
}

export interface ManifestLoad {
  manifest: Manifest | null;
  /** Where it was read from, for operator diagnostics. */
  path: string | null;
  /** Why there is no usable manifest. Null when one loaded cleanly. */
  problem: string | null;
}

let cached: ManifestLoad | undefined;

function load(): ManifestLoad {
  const tried: string[] = [];

  for (const path of candidatePaths()) {
    tried.push(path);
    if (!existsSync(path)) continue;

    try {
      const parsed = Manifest.safeParse(JSON.parse(readFileSync(path, "utf8")));
      if (!parsed.success) {
        return {
          manifest: null,
          path,
          problem: `Manifest at ${path} is malformed: ${parsed.error.issues
            .map(i => `${i.path.join(".") || "(root)"} ${i.message}`)
            .join("; ")}`,
        };
      }
      return { manifest: parsed.data as Manifest, path, problem: null };
    } catch (err) {
      return {
        manifest: null,
        path,
        problem: `Manifest at ${path} could not be read: ${(err as Error).message}`,
      };
    }
  }

  return {
    manifest: null,
    path: null,
    problem:
      `No MakeEmoji manifest found (looked in: ${tried.join(", ")}). ` +
      `Run the discovery script from a host that can reach makeemoji.com — ` +
      `see providers/makeemoji/README.md.`,
  };
}

/** The manifest, loaded once per process. */
export function getManifest(): ManifestLoad {
  if (cached === undefined) {
    cached = load();
    if (cached.problem) logger.warn({ problem: cached.problem }, "MakeEmoji manifest unavailable");
  }
  return cached;
}

/** Drop the cache so the next read re-reads from disk. Used by tests and tooling. */
export function reloadManifest(): ManifestLoad {
  cached = undefined;
  return getManifest();
}

/** Inject a manifest directly, bypassing the filesystem. Tests only. */
export function setManifestForTesting(manifest: Manifest | null, problem = "injected"): void {
  cached = manifest
    ? { manifest, path: "(injected)", problem: null }
    : { manifest: null, path: null, problem };
}

/**
 * Why this manifest can't drive a generation, or null when it can.
 *
 * "Verified" is not enough on its own: a discovery run that found the page but
 * no file input produced a manifest we still cannot use.
 */
export function manifestProblem(manifest: Manifest | null): string | null {
  if (!manifest) return "no manifest loaded";
  if (!manifest.verified) {
    return "manifest is unverified — discovery has not been run against the live site yet";
  }
  const hasApi = manifest.api !== null && !manifest.api.requiresBrowserSession;
  const hasBrowser = manifest.browser.fileInputSelector !== null;
  if (!hasApi && !hasBrowser) {
    return "manifest has neither a usable API endpoint nor a file-input selector";
  }
  if (!manifest.controls.animation?.values.length) {
    return "manifest lists no animation values";
  }
  return null;
}

/** The control spec for one option, when discovery found it. */
export function controlFor(manifest: Manifest, key: OptionKey): ControlSpec | undefined {
  return manifest.controls[key];
}

/** The values MakeEmoji accepts for one option, as discovered. */
export function valuesFor(manifest: Manifest | null, key: OptionKey): string[] {
  return manifest?.controls[key]?.values.map(v => v.value) ?? [];
}

/**
 * Resolve a user-supplied value against what MakeEmoji actually accepts.
 * Matches on value first, then label, both case-insensitively. Returns null when
 * the option is unknown to this manifest — the caller decides whether that is an
 * error or simply a setting to skip.
 */
export function resolveValue(
  manifest: Manifest | null, key: OptionKey, wanted: string | undefined,
): string | null {
  if (wanted === undefined) return null;
  const control = manifest?.controls[key];
  if (!control) return null;

  const needle = wanted.trim().toLowerCase();

  const exact = control.values.find(
    v => v.value.toLowerCase() === needle || v.label?.toLowerCase() === needle,
  );
  if (exact) return exact.value;

  // MakeEmoji decorates its own option text — sizes read `"⬜ 64px"`, directions
  // `"➡️ Right"`. A caller passing a bare `64` or `right` means the same thing,
  // so fall back to comparing the values with the decoration stripped. Labels
  // usually carry the plain form already; this covers the controls where they
  // do not.
  const plainNeedle = plain(needle);
  if (!plainNeedle) return null;

  const loose = control.values.find(
    v => plain(v.value) === plainNeedle || plain(v.label ?? "") === plainNeedle,
  );
  return loose?.value ?? null;
}

/**
 * Reduce an option's display text to its comparable core: lower-cased, with
 * emoji, punctuation and a trailing unit removed. `"⬜ 64px"` and `"64"` both
 * become `"64"`; `"➡️ Right"` and `"right"` both become `"right"`.
 */
function plain(text: string): string {
  const stripped = text
    .toLowerCase()
    // Anything that is not a letter, digit or dot is decoration for our purposes.
    .replace(/[^a-z0-9.]+/gi, "")
    .trim();
  // A pure measurement loses its unit so `64px` matches `64`.
  const measurement = /^(\d+(?:\.\d+)?)(px|pt|em|rem)?$/.exec(stripped);
  return measurement?.[1] ?? stripped;
}

export { OPTION_KEYS };
